(* ::Package:: *)

(* ::Input:: *)
(*SetOptions[Plot,*)
(* Axes -> False,*)
(* Frame -> True,*)
(* FrameStyle -> Directive[Thickness[0.003]],*)
(* PlotStyle -> {*)
(*   Directive[Blue, Thickness[0.003]],*)
(*   Directive[Green, Thickness[0.003]],*)
(*   Directive[Red, Thickness[0.003]],*)
(*   Directive[Cyan, Thickness[0.003]],*)
(*   Directive[Magenta, Thickness[0.003]],*)
(*   Directive[Yellow, Thickness[0.003]],*)
(*   Directive[Black, Thickness[0.003]],*)
(*   Directive[Blue, Thickness[0.003]]},*)
(* ImageSize -> {(1 + Sqrt[5])/2, 1}*800, (* Golden ratio *) *)
(* BaseStyle -> {FontFamily -> "Helvetica", *)
(*   FontSize -> *)
(*    34}]; (* Default plot options *)*)
(*(* 6/17/11: The last PlotStyle is the same as the first.  Otherwise, where there is only one line in a plot,the PlotStyle in the legend doesn't seem to match the PlotStyle in the plot. *)*)
(*(* 6/17/11: Unfortunately, the dashing of the lines in the legend doesn't match the dashing of the lines in the plot, so this can't be used:*)
(*PlotStyle->{Directive[Blue,Dashing[{1,0}],Thickness[0.003]],*)
(*Directive[Green,Dashing[{0.015,0.015}],Thickness[0.003]],*)
(*Directive[Red,Dashing[{0.005,0.005}],Thickness[0.003]],*)
(*Directive[Cyan,Dashing[{0.015,0.010,0.005,0.010}],Thickness[0.003]],*)
(*Directive[Magenta,Dashing[{1,0}],Thickness[0.003]],*)
(*Directive[Yellow,Dashing[{0.005,0.005}],Thickness[0.003]],*)
(*Directive[Black,Dashing[{0.015,0.010,0.005,0.010}],Thickness[0.003]],*)
(*Directive[Blue,Dashing[{1,0}],Thickness[0.003]]}*)
(**)*)
(*(* 10/2/11: Updated the formatting to match that of matplotlib. *)*)
(*(* 10/2/11: ImageSize needs to be large enough so that the PNGs are exported with sufficient quality. *)*)
